name: LWJGL Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  JEMALLOC_PARAMS: --with-jemalloc-prefix=je_ --disable-stats --disable-fill --disable-cxx

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
#         ARCH: [x64, arm32, arm64, mips64]
        ARCH: [powerpc64le]
        include:
          # -----
#           - ARCH: x64
#             PACKAGES:
#             CC:
#             EXTRA_PARAMS:
#             HOST: x86_64-pc-linux-gnu
#             STRIP: strip
          # -----
#           - ARCH: arm32
#             PACKAGES: gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
#             CC: CC=arm-linux-gnueabihf-gcc
#             EXTRA_PARAMS:
#             HOST: arm-unknown-linux-gnueabihf
#             STRIP: arm-linux-gnueabihf-strip
          # -----
#           - ARCH: arm64
#             PACKAGES: gcc-aarch64-linux-gnu
#             CC: CC=aarch64-linux-gnu-gcc
#             EXTRA_PARAMS:
#             HOST: aarch64-unknown-linux-gnu
#             STRIP: aarch64-linux-gnu-strip
          # -----
#           - ARCH: mips64
#             PACKAGES: gcc-mips64el-linux-gnuabi64
#             CC: CC=mips64el-linux-gnuabi64-gcc
#             EXTRA_PARAMS: --with-lg-page=14
#             HOST: mips64el-unknown-linux-gnu
#             STRIP: mips64el-linux-gnuabi64-strip
          # -----
          - ARCH: powerpc64le
            PACKAGES: gcc-powerpc64le-linux-gnu
            CC: CC=powerpc64le-linux-gnu-gcc
            EXTRA_PARAMS:
            HOST: powerpc64le-unknown-linux-gnu
            STRIP: powerpc64le-linux-gnu-strip
    env:
      LWJGL_ARCH: ${{matrix.ARCH}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: sudo apt-get -yq install ${{matrix.PACKAGES}}
        name: Install dependencies
        if: ${{matrix.PACKAGES != ''}}
      - run: |
          ${{matrix.CC}} CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ./autogen.sh ${{env.JEMALLOC_PARAMS}} ${{matrix.EXTRA_PARAMS}} --disable-initial-exec-tls --host=${{matrix.HOST}}
        name: Configure build
      - run: |
          make
          ${{matrix.STRIP}} lib/libjemalloc.so
        name: Build
      - run: aws s3 cp lib/libjemalloc.so s3://darren-lwjgl-build/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload artifact
#       - run: |
#           git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libjemalloc.so.git
#           aws s3 cp libjemalloc.so.git s3://lwjgl-build/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
#         name: Upload git revision

  
